
# [Choice] Debian version (use bullseye on local arm64/Apple Silicon): bullseye, buster
FROM mcr.microsoft.com/devcontainers/base:0.202-bullseye

COPY run-first-notice.txt /usr/local/etc/vscode-dev-containers/first-run-notice.txt

# ** [Optional] Uncomment this section to install additional packages. **
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

